#!/bin/bash
source ./init
ENVIRONMENT=$1
if [ -z "$ENVIRONMENT" ]; then
  echo "You must pass the stack environment name"
  exit 1
fi
if [ $ENVIRONMENT == production ]; then
  BUCKET_NAME=softcraft.ca
else
  BUCKET_NAME=$ENVIRONMENT.softcraft.ca
fi
aws s3 sync src s3://$BUCKET_NAME
